#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

sxhkd &
$HOME/.config/polybar/launch.sh --material &

#bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config presel_border_color "#000000"
bspc config focus_follows_pointer true
#bspc config normal_border_color "#5E81AC"
bspc config normal_border_color "#96CDFB"
bspc config focused_border_color "#89DCEB"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
